### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by danfox01** [Baltimore-County-Government/dotgov-components#10] opened 2019-04-08 21:51 UTC
Similar to #6, USTPO has excellent guidance on form usage. With the exception of a few changes, I'd like to replicate these usage guidelines as much as possible.

**Requirements**

http://uspto.github.io/designpatterns/1.x/docs/components/forms.html

**Comment by martypowell** [comment] 2019-08-09 13:34
duplicate of #11

**Closed as completed by martypowell** 2019-08-09 13:34 UTC
